"""item + create_at

Revision ID: 177b460eefdd
Revises: e224dd76c428
Create Date: 2019-03-22 17:21:34.685498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177b460eefdd'
down_revision = 'e224dd76c428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
